import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NotificationPage from './components/Notification'
import NavBar from './components/NavBar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Delivor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NotificationPage/>
     
      <NavBar/>
      {children}
      <Footer/>
      </body>
    
    </html>
  )
}
